name: Build and push image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  AZURE_CONTAINER_REGISTRY: "acaacr"
  RESOURCE_GROUP: "aca"
  IMAGE_NAME: "hello-world-fastapi"

jobs:
  buildImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ env.AZURE_CONTAINER_REGISTRY }}/hello-world-fastapi:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .