name: Build and push image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env: 
  AZURE_CONTAINER_REGISTRY: "acaacr"
  RESOURCE_GROUP: "aca"
  IMAGE_NAME: "hello-world-fastapi"

jobs:
  buildImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_NAME .
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          docker push $IMAGE_NAME